### ISSUE TITLE
Not Compatible with SonarQube 6.x

### ISSUE THREAD

**Issue by dbt4u** [adfemg/sonarqube-ojaudit#9]
Hello together,

do you have plans to update to SonarQube 6.x? At the moment it's only 3.0. Or do you can estimate what kind of effort this could be?

**Comment by RichardOlrichs** [comment]
Hey CraftOz, 
We got a branch that works against 5.6 & 6.0.
I will try to make an official release this week, shouldn't be too much effort.

Regards,
Richard

**Comment by RichardOlrichs** [comment]
See: https://github.com/adfemg/sonarqube-ojaudit/releases/tag/2.0

Please let me know if you have any comments/issues/remarks.

Richard

**Comment by dbt4u** [comment]
Great! With this 2.0 Version SonarQube 6.2 will start. Now I can dive deeper into ojauditing with SonarQube. Thanx-a-lot.
